### ISSUE TITLE
[Hinojosa] Errores y advertencias

### ISSUE THREAD

**Issue by ChrisChV** [RGiskard/SilaboCSUNSA#4]
### Mensaje del profesor

Tengo algunos errores y advertencia que no sé cómo solucionar.

### Task

Esos errores y advertencias aparecen en la sección 6.CONTENIDOS de la plantilla dufa.tex. Se tiene que revisar la plantilla y encontrar el problema, para que ya no sigan apareciendo los errores y advertencias.

### TODO

- [ ] Revisar la plantilla y encontrar el problema.
- [ ] Solucionar el problema.

**Comment by karldivad** [comment]
sin errores..ok
pero errores del usuario no son manejables en latex
peor si son warnings. siempre habrá siempre hay.

**Comment by ChrisChV** [comment]
Eran esos errores de `Undefined control sequence` que aparece en la sección 6. El profesor Hinojosa no ha usado tus comandos por que salían esos errores. Ha usado puro sections y enumerates.

**Comment by karldivad** [comment]
but it worked!!

**Comment by karldivad** [comment]
fixed directly!
It was and error on `\newcommand` definition on `\Unidad`, `\Tema` and `\Capitulo`.
```
\normalfont\medium\bfseries
```
'\medium' hadn't been recognize by LaTeX
replaced with:
```
\normalfont\mdseries
```
